version: '3'

services:
  lion-app:
    container_name: lion-app-dc
    build:
      context: .
      dockerfile: Dockerfile_django
    image: lion-app
    volumes:
      # 현재 폴더를 컨테이너의 /app 경로와 연결하여 공유
      - .:/app
       # lion-app 컨테이너의 /var/www/html/static를 볼륨으로 정의
      - lion-app-static:/var/www/html/static 
    ports:
      - 8000:8000
    command:
      - "/start"

  nginx:
    container_name: lion-nginx-dc
    build:
      context: .
      dockerfile: Dockerfile_nginx_ubt
    image: lion-nginx
    volumes:
      # nginx 컨테이너의 /var/www/html/static에 lion-app 컨테이너의 볼륨을 공유
      - lion-app-static:/var/www/html/static 
    ports:
      - 8888:80

volumes:
  # 볼륨 정의
  lion-app-static:

