FROM python:3.11-alpine

ARG APP_HOME=/app

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN mkdir ${APP_HOME}
WORKDIR ${APP_HOME}

RUN apk add --no-cache --upgrade bash

COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . ${APP_HOME}

COPY ./script/start /start
RUN sed -i 's/\r$//g' /start
RUN chmod +x /start

RUN python manage.py collectstatic --no-input

CMD [ "python", "--version"]
