# Not use

FROM nginx:latest

RUN apt-get update && apt install -y vim

# RUN echo "\ndaemon off;" >> /etc/nginx/nginx.conf
COPY ./nginx.conf /etc/nginx/nginx.conf

COPY ./config/django.nginx /etc/nginx/sites-available/django
RUN mkdir /etc/nginx/sites-enabled
RUN ln -s /etc/nginx/sites-available/django /etc/nginx/sites-enabled/django

CMD ["nginx"]

EXPOSE 80
EXPOSE 443