version: '3'

services:
  lion-app:
    depends_on:
      - postgres
    container_name: lion-app-dc
    build:
      context: .
      dockerfile: Dockerfile_django
    image: lion-app
    volumes:
      - ~/.aws:/root/.aws:ro
      - .:/app
      - lion-app-static:/var/www/html/static
    ports:
      - 8000:8000
    command:
      - "/start"
    env_file:
      - ./.envs/local/django
      - ./.envs/local/db
      - ./.envs/local/server
      - ./.envs/prod/ncp
    environment:
      - AWS_SECRET_NAME=like/lion/lecture


  nginx:
    restart: always
    depends_on:
      - lion-app
    container_name: lion-nginx-dc
    build:
      context: .
      dockerfile: Dockerfile_nginx_ubt
    image: lion-nginx
    volumes:
      - lion-app-static:/var/www/html/static 
    ports:
      - 8888:80
    env_file:
      - ./.envs/local/server

  postgres:
    container_name: postgres-dc
    image: postgres:15
    ports:
      - 5432:5432
    env_file:
      - ./.envs/local/db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    container_name: prometheus
    depends_on:
      - lion-app
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./monitoring:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.console.templates=/etc/proemtheus/consoles
      - --storage.tsdb.retention.time=10d
      - --storage.tsdb.retention.size=1GB
      - --web.enable-admin-api

volumes:
  lion-app-static:
  postgres_data:
