name: CD using Docker Image

on:
    push:
        tags:
            - "*.*.*"

env:
    IMAGE: ${{ vars.NCR_HOST }}/lion-app
    IMAGE_TAG: ${{ vars.NCR_HOST }}/lion-app:latest
    CONTAINER_NAME: lion-app-dc

jobs:
    deploy:
        name: deploy the new version
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Helm repository
              uses: actions/checkout@v3
              with:
                repository: 25th-Night/lion-k8s
                ref: main
                token: ${{ secrets.PAT }}

            - name: Update appVersion
              run: |
                sed -ie "s/appVersion.*/appVersion: ${{ github.ref_name }}/g" lionp/Chart.yaml
                cat lionp/Chart.yaml
              shell: bash

            - name: Commit files
              run: |
                git config --local user.email "brown_eyed87@naver.com"
                git config --local user.name "25th-Night"
                git commit -a -m "Add changes"
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                repository: 25th-Night/lion-k8s
                branch: main