name: CI

on:
    pull_request:
    push:
        branches:
            - main
    release:
        types:
            - released

env:
    IMAGE: ${{ vars.NCR_HOST }}/lion-app
    IMAGE_TAG: ${{ vars.NCR_HOST }}/lion-app:latest
    CONTAINER_NAME: lion-app-dc

jobs:
    lint:
        name: Check lint (black)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: Install black
              run: pip install black

            - name: check black
              run: black --check .


    build:
        needs: lint
        name: build image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: test
              run: |
                docker compose -f docker-compose_test.yml up -d --build
                docker compose -f docker-compose_test.yml exec lion-app python manage.py test

            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                  registry: ${{ vars.NCR_HOST }}
                  username: ${{ secrets.NCP_ACCESS_KEY_ID }}
                  password: ${{ secrets.NCP_SECRET_ACCESS_KEY }}

            - name: Get current timestamp
              id: image-tag
              run: echo "TIMESTAMP=$(date "+%s")" >> "$GITHUB_OUTPUT"

            - name: Build and Push
              uses: docker/build-push-action@v4
              with:
                context: .
                tags: ${{ env.IMAGE_TAG }},${{ env.IMAGE }}:${{ steps.image-tag.outputs.TIMESTAMP }},${{ env.IMAGE }}:${{ github.event.release.tag_name }}
                file: Dockerfile_django
                push: true

            - name: post test
              if: ${{ always() }}
              run: |
                docker compose -f docker-compose_test.yml down