name: CI

on:
    pull_request:
    push:
        branches:
            - main

env:
    IMAGE: ${{ vars.NCR_HOST }}/lion-app
    IMAGE_TAG: ${{ vars.NCR_HOST }}/lion-app:latest
    CONTAINER_NAME: lion-app-dc

jobs:
    build:
        name: build image
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v3

            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                  registry: ${{ vars.NCR_HOST }}
                  username: ${{ secrets.NCP_ACCESS_KEY_ID }}
                  password: ${{ secrets.NCP_SECRET_ACCESS_KEY }}

            - name: Get current timestamp
              id: image-tag
              run: echo "TIMESTAMP=$(date "+%s")" >> "$GITHUB_OUTPUT"

            - name: Build and Push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  tags: ${{ env.IMAGE_TAG }},${{ env.IMAGE }}:${{ steps.image-tag.outputs.TIMESTAMP }}
                  file: Dockerfile_django
                  push: false
