name: CI

on:
    pull_request:
    push:
        branches:
            - main

env:
    IMAGE: ${{ vars.NCR_HOST }}/lion-app
    IMAGE_TAG: ${{ vars.NCR_HOST }}/lion-app:latest
    CONTAINER_NAME: lion-app-dc

jobs:
    lint:
        name: Check lint (black)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: Install black
              run: pip install black

            - name: check black
              run: black --check .


    build:
        needs: lint
        name: build image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: ${{ vars.NCR_HOST }}
                username: ${{ secrets.NCP_ACCESS_KEY_ID }}
                password: ${{ secrets.NCP_SECRET_ACCESS_KEY }}

            - name: Get current timestamp
              id: image-tag
              run: echo "TIMESTAMP=$(date "+%s")" >> "$GITHUB_OUTPUT"

            - name: Build
              run: |
                docker build -f Dockerfile_django -t test-lion:test .

            - name: Run Test
              run: |
                docker run -d \
                -e DJANGO_SETTINGS_MODULE=config.settings.test \
                --name test \
                test-lion:test python --version
                docker exec test python manage.py test

            - name: post test
              if: ${{ always() }}
              run: |
                docker stop test && docker rm test && docker rmi test-lion:test