name: CD using Docker Image

on:
    push:
        branches:
            - main

jobs:
    # Build Image / Push Image to NCR
    build-push-images:
        name: build images and push to NCR
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v3
            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                  registry: ${{ secrets.NCR_HOST }}
                  username: ${{ secrets.NCP_ACCESS_KEY_ID }}
                  password: ${{ secrets.NCP_SECRET_ACCESS_KEY }}
            - name: Build and Push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  tags: browneyed.kr.ncr.ntruss.com/lion-app:latest
                  file: Dockerfile_django
                  push: true
