name: call workflow

on:
    workflow_dispatch:

jobs:
    get-name:
        name: echo name1
        runs-on: ubuntu-latest
        steps:
            - run: echo "This workflow is ${{ github.workflow }}"

    call-workflow:
        uses: ./.github/workflows/lesson4.yml
