name: CD using Docker Image

on:
    push:
        branches:
            - main

jobs:
    # Build Image / Push Image to NCR
    build-push-images:
        name: build images and push to NCR
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v3
            - name: build django images
              working-directory: .
              run: |
                  docker build -f Dockerfile_django --tag browneyed.kr.ncr.ntruss.com/lion-app:latest .
                  docker build -f Dockerfile_nginx --tag browneyed.kr.ncr.ntruss.com/lion-nginx:latest .
            - name: Login to ECR
              uses: docker/login-action@v2
              with:
                  registry: ${{ secrets.NCR_HOST }}
                  username: ${{ secrets.NCP_ACCESS_KEY_ID }}
                  password: ${{ secrets.NCP_SECRET_ACCESS_KEY }}
            - name: push images to NCR
              working-directory: .
              run: |
                  docker push browneyed.kr.ncr.ntruss.com/lion-app:latest
                  docker push browneyed.kr.ncr.ntruss.com/lion-nginx:latest

    # Pull Image From NCR / Run new container
    pull-images-and-run-container:
        name: pull images from NCR and run container
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v3
            - name: pull image from NCR and docker-compose up
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.NCP_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  script: |
                      cd dj_sample_drf
                      git pull origin main
                      docker pull browneyed.kr.ncr.ntruss.com/lion-app:latest
                      docker pull browneyed.kr.ncr.ntruss.com/lion-nginx:latest
                      docker-compose -f docker-compose_prod.yml up -d
