name: lesson1

on:
    push:
    pull_request:

jobs:
    echo-event:
        name: echo event
        runs-on: ubuntu-latest
        steps:
            - name: get event
              run: |
                  echo "This event is ${{github.event_name}}"
                  echo "This event is $GITHUB_EVENT_NAME"
            - name: echo github context
              run: echo "${{github.repositoryUrl}}"
            - name: list files
              run: ls -al

    docker-compose-build:
        name: docker compose build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: list files
              run: ls -al
            - name: install docker
              run: |
                  sudo apt-get install
                  sudo apt-get upgrade
                  sudo apt-get -y install docker.io
                  sudo service docker start
            - name: install docker-compose
              run: sudo apt-get -y install docker-compose
            - name: docker compose
              run: docker-compose up -d --build
