name: lesson1

on:
    workflow_dispatch:

jobs:
    echo-event:
        name: echo event
        runs-on: ubuntu-latest
        steps:
            - name: get event
              run: |
                  echo "This event is ${{github.event_name}}"
                  echo "This event is $GITHUB_EVENT_NAME"

    docker-build:
        if: ${{ ! github.event.act }}
        name: docker build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v2
            - name: Build and Export
              uses: docker/build-push-action@v4
              with:
                  context: .
                  tags: lion-app:latest
                  outputs: type=docker, dest=/tmp/lion_app.tar
                  file: Dockerfile_django
            - name: upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: lion-app
                  path: /tmp/lion_app.tar
            - name: docker images
              if: ${{ always() }}
              run: |
                  docker load --input /tmp/lion_app.tar
                  docker images lion-app

    docker-images:
        if: ${{ !github.event.act }}
        needs: docker-build
        name: docker images
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: lion-app
                  path: /tmp
            - name: load images
              run: docker load --input /tmp/lion_app.tar
            - name: docker images
              run: docker images lion-app
